--1.
 SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "이름",ENTRANCE_DATE AS "입학년도"
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = 002
 ORDER BY 3 ASC;
 
 --2.
 SELECT PROFESSOR_NAME AS "이름" ,PROFESSOR_SSN AS "주민등록번호"
 FROM TB_PROFESSOR
 WHERE PROFESSOR_NAME NOT LIKE '___'
 ORDER BY 1;
 
 --3. 
 SELECT PROFESSOR_NAME AS "이름", SUBSTR(PROFESSOR_SSN,1,2) AS "나이"
 FROM TB_PROFESSOR
 WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN,1,2)));
 
 --4. 
 SELECT SUBSTR(PROFESSOR_NAME,2,2) AS "이름"
 FROM TB_PROFESSOR;
 
 --5.
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE  EXTRACT(YEAR FROM TO_DATE(SUBSTR(ENTRANCE_DATE,1,8))) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) > 19;
 
 --6.
 SELECT TO_CHAR(TO_DATE('2020/12/25','YYYY/MM/DD'), 'DAY') AS "2020년 크리스마스 요일"
 FROM DUAL;
 
 --7. TO_DATE('99/10/11','YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD')은 각각 몇 년 몇 월 며칠을 의미할까?
 -- 문제가 의미하는 바가 뭐지...?
 -- 1999년 10월 11일....1949년 10월 11일..
 -- 또 TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD') 은 각각 몇 년 몇 월 며칠을 의미할까?

 --8.
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE SUBSTR(STUDENT_NO,1,1) NOT LIKE 'A%';
 
 --9.
 SELECT ROUND(AVG(NVL(POINT,0)),1) AS "평점"
 FROM TB_GRADE
 WHERE STUDENT_NO = 'A517178';
 
 --10.
 SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
 FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY DEPARTMENT_NO ASC;
 
 --11.
 SELECT COUNT(*)
 FROM TB_STUDENT
 GROUP BY COACH_PROFESSOR_NO
 HAVING COACH_PROFESSOR_NO IS NULL;
 
 --12.
SELECT SUBSTR(TERM_NO,1,4) AS "년도", ROUND(AVG(NVL(POINT, 0)),1) AS "년도별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4) ASC;

--13. 
SELECT DEPARTMENT_NO AS "학과코드명", COUNT(*) AS "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

--14.
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME ASC;

--15. 
SELECT SUBSTR(TERM_NO,1,4) AS "년도", SUBSTR(TERM_NO,5,2) AS "학기", ROUND(AVG(NVL(POINT, 0)),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113';
GROUP BY ROLLUP SUBSTR(TERM_NO,1,4);
 
 
 
 
 
 