--1.
 SELECT STUDENT_NO AS "학번",STUDENT_NAME AS "이름",ENTRANCE_DATE AS "입학년도"
 FROM TB_STUDENT
 WHERE DEPARTMENT_NO = 002
 ORDER BY 3 ASC;
 
 --2.
 SELECT PROFESSOR_NAME AS "이름" ,PROFESSOR_SSN AS "주민등록번호"
 FROM TB_PROFESSOR
 WHERE PROFESSOR_NAME NOT LIKE '___'
 ORDER BY 1;
 
 --3. 
 SELECT PROFESSOR_NAME AS "이름", SUBSTR(PROFESSOR_SSN,1,2) AS "나이"
 FROM TB_PROFESSOR
 WHERE MONTH_BETWEEN(SUBSTR(PROFESSOR_SSN, 8, 2),'23')/12;
 
 --4. 
 SELECT SUBSTR(PROFESSOR_NAME,2,2) AS "이름"
 FROM TB_PROFESSOR;
 
 --5.
 SELECT STUDENT_NAME, SUBSTR(STUDENT_SSN,1,2) AS "나이"
 FROM TB_STUDENT;
 